server:
    port: 8083
spring:
  cloud:
      config:
          uri: http://localhost:8888
  profiles:
      active: development
  application:
      name: TMS-OrderService
eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true