server:
    port: 8082
spring:
    cloud:
        config:
            uri: http://localhost:8888
    application:
        name: TMS-AuthService
    profiles:
        active: development
    redis:
        host: localhost
        port: 6379